alfabeto = ["A", "B", "C", "D", "E", "F", "G", "H", 
          "I", "J", "K", "L", "M", "N", "O", "P", 
          "Q", "R", "S", "T", "U", "V", "W", "X", 
          "Y", "Z"]
silabas = ["A", "AL", "AM", "AN", "AR", "AS", 
           "E", "EL", "EM", "EN", "ER", "ES", 
           "I", "IL", "IM", "IN", "IR", "IS", 
           "O", "OL", "OM", "ON", "OR", "OS", 
           "U", "UL", "UM", "UN", "UR", "US", 
           "B", "BA", "BE", "BI", "BO", "BU", 
           "C", "CA", "CE", "CI", "CO", "CU", 
           "D", "DA", "DE", "DI", "DO", "DU", 
           "F", "FA", "FE", "FI", "FO", "FU", 
           "G", "GA", "GE", "GI", "GO", "GU", 
           "H", "HA", "HE", "HI", "HO", "HU", 
           "J", "JA", "JE", "JI", "JO", "JU", 
           "L", "LA", "LE", "LI", "LO", "LU", 
           "M", "MA", "ME", "MI", "MO", "MU", 
           "N", "NA", "NE", "NI", "NO", "NU", 
           "P", "PA", "PE", "PI", "PO", "PU", 
           "R", "RA", "RE", "RI", "RO", "RU", 
           "S", "SA", "SE", "SI", "SO", "SU", 
           "T", "TA", "TE", "TI", "TO", "TU", 
           "V", "VA", "VE", "VI", "VO", "VU", 
           "X", "XA", "XE", "XI", "XO", "XU", 
           "Z", "ZA", "ZE", "ZI", "ZO", "ZU"]